USE dgcore;

INSERT INTO item (id, label, description, event, weight, image, stack, category, `unique`, usable, price, is_trade, is_remove, metadata) VALUES
('weapon_unarmed', '素手', '何も装備していない状態。パンチやキックで攻撃可能。', NULL, 1000, 'placeholder.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_dagger', 'ダガー', '鋭い刃を持つ短剣。素早い攻撃が可能。', NULL, 1000, 'weapon_dagger.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bat', 'バット', '本来はスポーツ用だが、近接戦闘でも活躍。', NULL, 1000, 'weapon_bat.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bottle', '割れたボトル', '割れたガラス瓶。鋭利な部分で攻撃。', NULL, 1000, 'weapon_bottle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_crowbar', 'バール', '重くて頑丈な鉄棒。殴打やこじ開けに使える。', NULL, 1000, 'weapon_crowbar.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_flashlight', '懐中電灯', '暗闇を照らすだけでなく、近接武器にもなる。', NULL, 1000, 'weapon_flashlight.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_golfclub', 'ゴルフクラブ', 'ゴルフ用クラブ。振り回して攻撃可能。', NULL, 1000, 'weapon_golfclub.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_hammer', 'ハンマー', '釘打ちや破壊に使う工具。近接戦闘にも有効。', NULL, 1000, 'weapon_hammer.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_hatchet', '手斧', '片手で扱える小型の斧。威力が高い。', NULL, 1000, 'weapon_hatchet.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_knuckle', 'メリケンサック', '拳に装着して打撃力を強化する武器。', NULL, 1000, 'weapon_knuckle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_knife', 'ナイフ', '切る・刺す両方に使える万能な刃物。', NULL, 1000, 'weapon_knife.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_machete', 'マチェーテ', '重くて大きな刃のナタ。威力重視。', NULL, 1000, 'weapon_machete.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_switchblade', 'スイッチブレード', 'ボタン一つで刃が飛び出す小型ナイフ。', NULL, 1000, 'weapon_switchblade.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_nightstick', '警棒', '警察官が使用する特殊警棒。', NULL, 1000, 'weapon_nightstick.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_wrench', 'レンチ', '工具だが、殴打武器としても使える。', NULL, 1000, 'weapon_wrench.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_battleaxe', 'バトルアックス', '戦闘用の大型斧。破壊力抜群。', NULL, 1000, 'weapon_battleaxe.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_poolcue', 'ビリヤードキュー', 'ビリヤード用の棒。意外とリーチが長い。', NULL, 1000, 'weapon_poolcue.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_briefcase', 'ブリーフケース', '重要書類を入れるカバン。殴打にも使える。', NULL, 1000, 'weapon_briefcase.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_briefcase_02', 'スーツケース', '旅行用のカバン。武器としても利用可能。', NULL, 1000, 'weapon_briefcase2.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_garbagebag', 'ゴミ袋', '中身次第で凶器にもなるゴミ袋。', NULL, 1000, 'weapon_garbagebag.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_handcuffs', '手錠', '相手の動きを封じる拘束具。', NULL, 1000, 'weapon_handcuffs.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bread', 'バゲット', 'パン。なぜか武器になる。', NULL, 1000, 'baquette.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_stone_hatchet', 'ストーンハチェット', '石で作られた斧。原始的だが威力は十分。', NULL, 1000, 'weapon_stone_hatchet.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_candycane', 'キャンディケイン', 'お菓子の杖。見た目に反して意外と痛い。', NULL, 1000, 'weapon_candycane', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_pistol', 'ワルサーP99', '片手で扱える小型拳銃。扱いやすく初心者向け。', NULL, 1000, 'weapon_pistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_pistol_mk2', 'ピストルMk II', '改良型の小型拳銃。カスタマイズ性が高い。', NULL, 1000, 'weapon_pistol_mk2.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_combatpistol', 'コンバットピストル', '戦闘用に設計された拳銃。信頼性が高い。', NULL, 1000, 'weapon_combatpistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_appistol', 'APピストル', 'フルオート射撃が可能な拳銃。連射性能が魅力。', NULL, 1000, 'weapon_appistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_stungun', 'テーザー', '電気ショックで相手を一時的に無力化する非致死武器。', NULL, 1000, 'weapon_stungun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_pistol50', 'ピストル.50', '大口径の拳銃。高威力だが反動も大きい。', NULL, 1000, 'weapon_pistol50.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_snspistol', 'SNSピストル', '小型で隠し持ちやすい拳銃。携帯性重視。', NULL, 1000, 'weapon_snspistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_heavypistol', 'ヘビーピストル', '重量級の拳銃。威力と貫通力が高い。', NULL, 1000, 'weapon_heavypistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_vintagepistol', 'ビンテージピストル', 'クラシックなデザインの拳銃。コレクター向け。', NULL, 1000, 'weapon_vintagepistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_flaregun', 'フレアガン', '信号弾を発射するピストル。敵の目くらましにも。', NULL, 1000, 'weapon_flaregun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_marksmanpistol', 'マークスマンピストル', '高精度の単発ピストル。狙撃にも使える。', NULL, 1000, 'weapon_marksmanpistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_revolver', 'リボルバー', '複数発を連続で撃てる回転式拳銃。', NULL, 1000, 'weapon_revolver.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_revolver_mk2', 'リボルバーMk II', '改良型リボルバー。威力と精度が向上。', NULL, 1000, 'weapon_revolver_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_doubleaction', 'ダブルアクションリボルバー', '素早い連射が可能なリボルバー。', NULL, 1000, 'weapon_doubleaction.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_snspistol_mk2', 'SNSピストルMk II', '小型で隠し持ちやすい改良型拳銃。', NULL, 1000, 'weapon_snspistol_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_raypistol', 'アップンアトマイザー', 'エネルギー弾を発射する未来的な武器。', NULL, 1000, 'weapon_raypistol.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_ceramicpistol', 'セラミックピストル', 'セラミック製で金属探知機に反応しにくい拳銃。', NULL, 1000, 'weapon_ceramicpistol.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_navyrevolver', 'ネイビーリボルバー', 'クラシックな海軍用リボルバー。', NULL, 1000, 'weapon_navyrevolver.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_gadgetpistol', 'ペリコピストル', '特殊な装飾が施された限定ピストル。', NULL, 1000, 'weapon_gadgetpistol.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_pistolxm3', 'ピストルXM3', '最新型の高性能ピストル。', NULL, 1000, 'weapon_pistolxm3.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_microsmg', 'マイクロSMG', '小型で連射力の高いサブマシンガン。近距離戦に最適。', NULL, 1000, 'weapon_microsmg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_smg', 'SMG', '軽量で扱いやすいサブマシンガン。連射性能が高い。', NULL, 1000, 'weapon_smg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_smg_mk2', 'SMG Mk II', 'カスタマイズ性が高い改良型SMG。', NULL, 1000, 'weapon_smg_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_assaultsmg', 'アサルトSMG', '高い連射力と装弾数を誇るサブマシンガン。', NULL, 1000, 'weapon_assaultsmg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_combatpdw', 'コンバットPDW', '戦闘用に設計された高性能サブマシンガン。', NULL, 1000, 'weapon_combatpdw.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_machinepistol', 'マシンピストル', 'フルオート射撃が可能な小型自動拳銃。', NULL, 1000, 'weapon_machinepistol.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_minismg', 'ミニSMG', 'さらに小型化されたサブマシンガン。携帯性抜群。', NULL, 1000, 'weapon_minismg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_raycarbine', 'アンホーリー・ヘルブリンガー', 'エネルギー弾を発射する未来的なサブマシンガン。', NULL, 1000, 'weapon_raycarbine.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_pumpshotgun', 'ポンプ式ショットガン', 'ポンプアクション式のショットガン。近距離で絶大な威力。', NULL, 1000, 'weapon_pumpshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_sawnoffshotgun', 'ソードオフショットガン', '銃身を切り詰めたショットガン。取り回しやすい。', NULL, 1000, 'weapon_sawnoffshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_assaultshotgun', 'アサルトショットガン', '連射可能なショットガン。制圧力が高い。', NULL, 1000, 'weapon_assaultshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bullpupshotgun', 'ブルパップショットガン', 'コンパクトな設計のショットガン。', NULL, 1000, 'weapon_bullpupshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_musket', 'マスケット銃', '古風な火縄銃。ロマン重視。', NULL, 1000, 'weapon_musket.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_heavyshotgun', 'ヘビーショットガン', '高威力のショットガン。装弾数も多い。', NULL, 1000, 'weapon_heavyshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_dbshotgun', 'ダブルバレルショットガン', '2連発のショットガン。瞬間火力が高い。', NULL, 1000, 'weapon_dbshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_autoshotgun', 'オートショットガン', '自動射撃が可能なショットガン。', NULL, 1000, 'weapon_autoshotgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_pumpshotgun_mk2', 'ポンプ式ショットガンMk II', '改良型のポンプ式ショットガン。', NULL, 1000, 'weapon_pumpshotgun_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_combatshotgun', 'コンバットショットガン', '戦闘用ショットガン。連射力と威力を両立。', NULL, 1000, 'weapon_combatshotgun.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_assaultrifle', 'アサルトライフル', '歩兵用の自動小銃。バランスが良い。', NULL, 1000, 'weapon_assaultrifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_assaultrifle_mk2', 'アサルトライフルMk II', '改良型アサルトライフル。カスタム性が高い。', NULL, 1000, 'weapon_assaultrifle_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_carbinerifle', 'カービンライフル', '軽量で高精度な自動小銃。', NULL, 1000, 'weapon_carbinerifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_carbinerifle_mk2', 'カービンライフルMk II', '改良型カービンライフル。', NULL, 1000, 'weapon_carbinerifle_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_advancedrifle', 'アドバンスドライフル', '高性能なアサルトライフル。', NULL, 1000, 'weapon_advancedrifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_specialcarbine', 'スペシャルカービン', '汎用性の高いアサルトライフル。', NULL, 1000, 'weapon_specialcarbine.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bullpuprifle', 'ブルパップライフル', 'コンパクトな自動小銃。', NULL, 1000, 'weapon_bullpuprifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_compactrifle', 'コンパクトライフル', '小型化されたアサルトライフル。', NULL, 1000, 'weapon_compactrifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_specialcarbine_mk2', 'スペシャルカービンMk II', '改良型スペシャルカービン。', NULL, 1000, 'weapon_specialcarbine_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_bullpuprifle_mk2', 'ブルパップライフルMk II', '改良型ブルパップライフル。', NULL, 1000, 'weapon_bullpuprifle_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_militaryrifle', 'ミリタリーライフル', '軍用の高性能ライフル。', NULL, 1000, 'weapon_militaryrifle.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_mg', 'マシンガン', '連射力の高い自動火器。制圧力抜群。', NULL, 1000, 'weapon_mg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_combatmg', 'コンバットMG', '戦闘用マシンガン。高い連射力と威力。', NULL, 1000, 'weapon_combatmg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_gusenberg', 'トンプソンSMG', '通称トミーガン。クラシックなサブマシンガン。', NULL, 1000, 'weapon_gusenberg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_combatmg_mk2', 'コンバットMG Mk II', '改良型コンバットMG。', NULL, 1000, 'weapon_combatmg_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_sniperrifle', 'スナイパーライフル', '高精度・長距離射撃用ライフル。', NULL, 1000, 'weapon_sniperrifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_heavysniper', 'ヘビースナイパー', '高威力のスナイパーライフル。装甲車両にも有効。', NULL, 1000, 'weapon_heavysniper.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_marksmanrifle', 'マークスマンライフル', '高精度の単発ライフル。連射も可能。', NULL, 1000, 'weapon_marksmanrifle.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_remotesniper', 'リモートスナイパー', '遠隔操作可能なスナイパーライフル。', NULL, 1000, 'weapon_remotesniper.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_heavysniper_mk2', 'ヘビースナイパーMk II', '改良型ヘビースナイパー。', NULL, 1000, 'weapon_heavysniper_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_marksmanrifle_mk2', 'マークスマンライフルMk II', '改良型マークスマンライフル。', NULL, 1000, 'weapon_marksmanrifle_mk2.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_rpg', 'RPG', 'ロケット弾を発射する携帯式ランチャー。', NULL, 1000, 'weapon_rpg.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_grenadelauncher', 'グレネードランチャー', '手榴弾を発射するランチャー。', NULL, 1000, 'weapon_grenadelauncher.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_grenadelauncher_smoke', 'スモークグレネードランチャー', '煙幕弾を発射するランチャー。', NULL, 1000, 'weapon_smokegrenade.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_minigun', 'ミニガン', '多連装の高速回転式機関銃。圧倒的な火力。', NULL, 1000, 'weapon_minigun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_firework', '花火ランチャー', '花火を打ち上げるランチャー。お祭り気分に。', NULL, 1000, 'weapon_firework.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_railgun', 'レールガン', '電磁力で弾丸を高速発射する未来兵器。', NULL, 1000, 'weapon_railgun.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_railgunxm3', 'レールガンXM3', '最新型のレールガン。', NULL, 1000, 'weapon_railgunxm3.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_hominglauncher', 'ホーミングランチャー', '自動追尾機能付きのロケットランチャー。', NULL, 1000, 'weapon_hominglauncher.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_compactlauncher', 'コンパクトランチャー', '小型のグレネードランチャー。', NULL, 1000, 'weapon_compactlauncher.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_rayminigun', 'ウィドウメーカー', 'エネルギー弾を連射する未来的な重火器。', NULL, 1000, 'weapon_rayminigun.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weapon_grenade', '手榴弾', '投げて爆発させる基本的な爆発物。', NULL, 1000, 'weapon_grenade.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_bzgas', 'BZガス', '催涙効果のあるガス弾。', NULL, 1000, 'weapon_bzgas.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_molotov', '火炎瓶', '火をつけて投げる即席爆弾。', NULL, 1000, 'weapon_molotov.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_stickybomb', 'C4爆弾', '貼り付けて起爆できる爆薬。', NULL, 1000, 'weapon_stickybomb.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_proxmine', 'プロックスマイン', '近接感知で爆発する地雷。', NULL, 1000, 'weapon_proximitymine.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_snowball', 'スノーボール', '雪玉。投げて遊ぶこともできる。', NULL, 1000, 'weapon_snowball.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_pipebomb', 'パイプ爆弾', '即席で作られた爆弾。', NULL, 1000, 'weapon_pipebomb.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_ball', 'ボール', '投げたり蹴ったりできるボール。', NULL, 1000, 'weapon_ball.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_smokegrenade', 'スモークグレネード', '煙幕を発生させる手榴弾。', NULL, 1000, 'weapon_c4.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_flare', 'フレアピストル', '信号用の発炎弾を発射するピストル。', NULL, 1000, 'weapon_flare.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_petrolcan', 'ガソリン缶', 'ガソリンを撒いて火をつけられる。', NULL, 1000, 'weapon_petrolcan.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_fireextinguisher', '消火器', '火を消すための装置。', NULL, 1000, 'weapon_fireextinguisher.png', 1, 'weapon', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weapon_hazardcan', '有害物質入りジェリー缶', '危険な液体が入った缶。', NULL, 1000, 'weapon_hazardcan.png', 1, 'weapon', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('clip_attachment', 'クリップ', '武器の装弾数を増やすアタッチメント。リロード頻度を減らし、継戦能力を向上させる。', NULL, 1000, 'clip_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('drum_attachment', 'ドラムマガジン', '大容量の弾倉。多くの弾を装填でき、長時間の射撃が可能になる。', NULL, 1000, 'drum_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('flashlight_attachment', 'フラッシュライト', '武器に装着するライト。暗所での視認性を向上させ、夜間や屋内戦闘で有利になる。', NULL, 1000, 'flashlight_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('suppressor_attachment', 'サプレッサー', '発砲音を抑えるアタッチメント。敵に気付かれにくく、ステルス行動に最適。', NULL, 1000, 'suppressor_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('smallscope_attachment', 'スモールスコープ', '近距離～中距離用の小型スコープ。照準精度を高める。', NULL, 1000, 'smallscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('medscope_attachment', 'ミディアムスコープ', '中距離戦闘向けのスコープ。標的をより正確に狙える。', NULL, 1000, 'medscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('largescope_attachment', 'ラージスコープ', '遠距離射撃に適した大型スコープ。スナイパーライフルなどで活躍。', NULL, 1000, 'largescope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('holoscope_attachment', 'ホロスコープ', 'ホログラフィック照準器。素早い照準合わせが可能で、近～中距離戦闘に有効。', NULL, 1000, 'holoscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('advscope_attachment', 'アドバンスドスコープ', '高性能スコープ。遠距離でも高い命中精度を発揮する。', NULL, 1000, 'advscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('nvscope_attachment', 'ナイトビジョンスコープ', '暗闇でも標的を視認できるスコープ。夜間戦闘で有利。', NULL, 1000, 'nvscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('thermalscope_attachment', 'サーマルスコープ', '熱源を感知して敵を見つけやすくするスコープ。煙や暗闇でも効果的。', NULL, 1000, 'thermalscope_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('flat_muzzle_brake', 'フラットマズルブレーキ', '反動を抑え、射撃時の安定性を向上させるマズルブレーキ。', NULL, 1000, 'flat_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('tactical_muzzle_brake', 'タクティカルマズルブレーキ', '戦術的なデザインのマズルブレーキ。反動制御に優れる。', NULL, 1000, 'tactical_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('fat_end_muzzle_brake', 'ファットエンドマズルブレーキ', '太めの先端が特徴のマズルブレーキ。反動を大きく軽減。', NULL, 1000, 'fat_end_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('precision_muzzle_brake', 'プレシジョンマズルブレーキ', '精密射撃向けのマズルブレーキ。命中精度を高める。', NULL, 1000, 'precision_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('heavy_duty_muzzle_brake', 'ヘビーデューティマズルブレーキ', '耐久性に優れたマズルブレーキ。連射時の制御性が向上。', NULL, 1000, 'heavy_duty_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('slanted_muzzle_brake', 'スランテッドマズルブレーキ', '斜め形状のマズルブレーキ。反動を効果的に分散。', NULL, 1000, 'slanted_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('split_end_muzzle_brake', 'スプリットエンド・マズルブレーキ', '先端が分かれたデザインのマズルブレーキ。反動軽減と制御性向上。', NULL, 1000, 'split_end_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('squared_muzzle_brake', 'スクエアドマズルブレーキ', '角ばった形状のマズルブレーキ。安定した射撃をサポート。', NULL, 1000, 'squared_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('bellend_muzzle_brake', 'ベルエンドマズルブレーキ', 'ベル型のマズルブレーキ。反動を抑え、連射時のブレを軽減。', NULL, 1000, 'bellend_muzzle_brake.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('barrel_attachment', 'バレル', '武器の銃身。射程や命中精度に影響を与える重要パーツ。', NULL, 1000, 'barrel_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('grip_attachment', 'グリップ', '武器の持ち手部分。安定性を高め、反動を抑える。', NULL, 1000, 'grip_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('comp_attachment', 'コンペンセイター', '銃口の跳ね上がりを抑えるアタッチメント。連射時の制御性が向上。', NULL, 1000, 'comp_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('luxuryfinish_attachment', 'ラグジュアリーフィニッシュ', '高級感のある装飾。武器の外観を豪華にカスタマイズ。', NULL, 1000, 'luxuryfinish_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('digicamo_attachment', 'デジタルカモ', 'デジタル迷彩柄のスキン。武器の外観をカスタマイズ。', NULL, 1000, 'digicamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('brushcamo_attachment', 'ブラッシュストロークカモ', '筆跡風の迷彩スキン。個性的な外観に変更。', NULL, 1000, 'brushcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('woodcamo_attachment', 'ウッドランドカモ', '森林迷彩柄のスキン。自然環境でのカモフラージュに最適。', NULL, 1000, 'woodcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('skullcamo_attachment', 'スカルカモ', 'ドクロ柄のスキン。インパクトのある外観に。', NULL, 1000, 'skullcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('sessantacamo_attachment', 'セッサンタノーヴェカモ', '特別デザインの迷彩スキン。個性を演出。', NULL, 1000, 'sessantacamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('perseuscamo_attachment', 'ペルセウスカモ', 'ペルセウスをモチーフにしたスキン。独自のデザイン。', NULL, 1000, 'perseuscamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('leopardcamo_attachment', 'レオパードカモ', 'ヒョウ柄のスキン。派手な外観にカスタマイズ。', NULL, 1000, 'leopardcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('zebracamo_attachment', 'ゼブラカモ', 'シマウマ柄のスキン。目立つデザイン。', NULL, 1000, 'zebracamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('geocamo_attachment', 'ジオメトリックカモ', '幾何学模様のスキン。モダンな印象。', NULL, 1000, 'geocamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('boomcamo_attachment', 'ブームカモ', '爆発をイメージしたスキン。派手な外観。', NULL, 1000, 'boomcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('patriotcamo_attachment', 'パトリオットカモ', '星条旗モチーフのスキン。アメリカンなデザイン。', NULL, 1000, 'patriotcamo_attachment.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_0', 'デフォルトティント', '標準/黒色の武器ティント。初期状態のカラー。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_1', 'グリーンティント', '緑色の武器ティント。外観をカスタマイズ。', NULL, 1000, 'weapontint_green.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_2', 'ゴールドティント', '金色の武器ティント。高級感を演出。', NULL, 1000, 'weapontint_gold.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_3', 'ピンクティント', 'ピンク色の武器ティント。個性的なカラー。', NULL, 1000, 'weapontint_pink.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_4', 'アーミーティント', '軍用風の武器ティント。ミリタリー感を強調。', NULL, 1000, 'weapontint_army.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_5', 'LSPDカラー', 'LSPD公式の武器カラー。警察気分を味わえる特別な塗装。', NULL, 1000, 'weapontint_lspd.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_6', 'オレンジカラー', '鮮やかなオレンジ色の武器カラー。目立ちたい時に最適。', NULL, 1000, 'weapontint_orange.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_7', 'プラチナカラー', '高級感あふれるプラチナ仕上げの武器カラー。', NULL, 1000, 'weapontint_plat.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_0', 'クラシックブラック（MK2）', 'MK2武器用の定番ブラックカラー。シンプルで渋い。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_1', 'クラシックグレー（MK2）', 'MK2武器用の落ち着いたグレーカラー。都会的な印象。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_2', 'クラシックツートン（MK2）', 'MK2武器用のツートンカラー。個性を出したい時に。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_3', 'クラシックホワイト（MK2）', 'MK2武器用のホワイトカラー。清潔感のある仕上がり。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_4', 'クラシックベージュ（MK2）', 'MK2武器用のベージュカラー。砂漠やアウトドアに最適。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_5', 'クラシックグリーン（MK2）', 'MK2武器用のグリーンカラー。自然に溶け込む迷彩風。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_6', 'クラシックブルー（MK2）', 'MK2武器用のブルーカラー。爽やかな印象を与える。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_7', 'クラシックアース（MK2）', 'MK2武器用のアースカラー。自然な雰囲気でカモフラージュに最適。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_8', 'クラシックブラウン&ブラック（MK2）', 'MK2武器用のブラウン&ブラックカラー。重厚感のある仕上がり。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_9', 'レッドコントラストティント', 'MK2武器用の赤いコントラストティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_10', 'ブルーコントラストティント', 'MK2武器用の青いコントラストティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_11', 'イエローコントラストティント', 'MK2武器用の黄色いコントラストティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_12', 'オレンジコントラストティント', 'MK2武器用のオレンジコントラストティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_13', 'ボールドピンクティント', 'MK2武器用の鮮やかなピンクティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_14', 'ボールドパープル＆イエロー ティント', 'MK2武器用の紫と黄色の鮮やかなティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_15', 'ボールドオレンジティント', 'MK2武器用の鮮やかなオレンジティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_16', 'ボールドグリーン＆パープル ティント', 'MK2武器用の緑と紫の鮮やかなティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_17', 'ボールドレッドフィーチャーズティント', 'MK2武器用の赤い特徴的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_18', 'ボールドグリーンフィーチャーズティント', 'MK2武器用の緑の特徴的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_19', 'ボールドシアンフィーチャーズティント', 'MK2武器用のシアンの特徴的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_20', 'ボールドイエローフィーチャーズティント', 'MK2武器用の黄色の特徴的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_21', 'ボールドレッド＆ホワイトティント', 'MK2武器用の赤と白の鮮やかなティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_22', 'ボールドブルー＆ホワイトティント', 'MK2武器用の青と白の鮮やかなティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_23', 'メタリックゴールドティント', 'MK2武器用の金属的なゴールドティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_24', 'メタリックプラチナティント', 'MK2武器用の金属的なプラチナティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_25', 'メタリックグレー＆ライラックティント', 'MK2武器用のグレーとライラックの金属的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_26', 'メタリックパープル＆ライムティント', 'MK2武器用の紫とライムの金属的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_27', 'メタリックレッドティント', 'MK2武器用の金属的な赤ティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_28', 'メタリックグリーンティント', 'MK2武器用の金属的な緑ティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_29', 'メタリックブルーティント', 'MK2武器用の金属的な青ティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_30', 'メタリックホワイト＆アクアティント', 'MK2武器用の白とアクアの金属的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_31', 'メタリックオレンジ＆イエローティント', 'MK2武器用のオレンジと黄色の金属的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weapontint_mk2_32', 'メタリックレッド＆イエローティント', 'MK2武器用の赤と黄色の金属的なティント。武器の外観をカスタマイズできる。', NULL, 1000, 'weapontint_black.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('pistol_ammo', 'ピストルの弾薬', 'ピストル用の弾薬。対応武器の弾数を補充できる。', NULL, 200, 'pistol_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('rifle_ammo', 'ライフルの弾薬', 'ライフル用の弾薬。対応武器の弾数を補充できる。', NULL, 1000, 'rifle_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('smg_ammo', 'サブマシンガンの弾薬', 'サブマシンガン用の弾薬。対応武器の弾数を補充できる。', NULL, 500, 'smg_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('shotgun_ammo', 'ショットガンの弾薬', 'ショットガン用の弾薬。対応武器の弾数を補充できる。', NULL, 500, 'shotgun_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('mg_ammo', 'マシンガンの弾薬', 'マシンガン用の弾薬。対応武器の弾数を補充できる。', NULL, 1000, 'mg_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('snp_ammo', 'スナイパーの弾薬', 'スナイパーライフル用の弾薬。対応武器の弾数を補充できる。', NULL, 1000, 'rifle_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('emp_ammo', 'EMP弾薬', 'EMPランチャー用の弾薬。電子機器を一時的に無力化できる。', NULL, 200, 'emp_ammo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('id_card', 'IDカード', '身分証明書。個人情報が記載されている。', NULL, 0, 'id_card.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('driver_license', '運転免許証', '車両の運転が許可されていることを示す証明書。', NULL, 0, 'driver_license.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('lawyerpass', '弁護士パス', '弁護士専用のパス。被疑者の代理が可能であることを示す。', NULL, 0, 'lawyerpass.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('weaponlicense', '武器所持許可証', '武器の所持が許可されていることを示す証明書。', NULL, 0, 'weapon_license.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('bank_card', '銀行カード', 'ATMの利用や口座へのアクセスに使用するカード。', NULL, 0, 'bank_card.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('security_card_01', 'セキュリティカードA', '特定の施設やエリアへのアクセスに必要なセキュリティカード。', NULL, 0, 'security_card_01.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('security_card_02', 'セキュリティカードB', '特定の施設やエリアへのアクセスに必要なセキュリティカード。', NULL, 0, 'security_card_02.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('tosti', 'チーズトースト', '体力や空腹を回復できる食料アイテム。', NULL, 200, 'tosti.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 80, "thirst": 0, "stress": 0}'),
('twerks_candy', 'トゥワークスキャンディ', '消費すると空腹を満たすことができるキャンディ。', NULL, 100, 'twerks_candy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 30, "thirst": 0, "stress": 0}'),
('snikkel_candy', 'スニッケルキャンディ', '消費すると空腹を満たすことができるキャンディ。', NULL, 100, 'snikkel_candy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 30, "thirst": 0, "stress": 0}'),
('sandwich', 'サンドイッチ', '体力や空腹を回復できる食料アイテム。', NULL, 200, 'sandwich.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 60, "thirst": 0, "stress": 0}'),
('water_bottle', '水のボトル', '喉の渇きを癒す飲料アイテム。', NULL, 500, 'water_bottle.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 80, "stress": 0}'),
('coffee', 'コーヒー', 'カフェインでスタミナを回復できる飲料。', NULL, 200, 'coffee.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 20, "stress": -10}'),
('kurkakola', 'コーラ', '喉の渇きを癒す飲料アイテム。', NULL, 500, 'cola.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 10, "thirst": 10, "stress": 0}'),
('beer', 'ビール', '飲むと気分が良くなる飲料アイテム。', NULL, 500, 'beer.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 10, "stress": -80}'),
('whiskey', 'ウイスキー', '飲むと気分が良くなる飲料アイテム。', NULL, 500, 'whiskey.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 10, "stress": -60}'),
('vodka', 'ウォッカ', '飲むと気分が良くなる飲料アイテム。', NULL, 500, 'vodka.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 10, "stress": -100}'),
('grape', 'ぶどう', '食べると空腹を満たすことができる果物。', NULL, 100, 'grape.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 30, "thirst": 5, "stress": 0}'),
('wine', 'ワイン', '飲むと気分が良くなる飲料アイテム。', NULL, 300, 'wine.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 10, "stress": -40}'),
('grapejuice', 'ぶどうジュース', 'Grape juice is said to be healthy', NULL, 200, 'grapejuice.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 40, "stress": 0}'),
('joint', 'ジョイント', 'Sidney would be very proud at you', NULL, 0, 'joint.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('cokebaggy', 'コカイン', '摂取すると一時的に幸福感を得られる違法薬物。', NULL, 0, 'cocaine_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('crack_baggy', 'クラック', '摂取すると一時的に幸福感を得られる違法薬物。', NULL, 0, 'crack_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('xtcbaggy', 'エクスタシー', '摂取すると一時的に多幸感を得られる違法薬物。', NULL, 0, 'xtc_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('coke_brick', 'コカインブリック', '取引や運搬に使われる大きなコカインの塊。所持は違法。', NULL, 1000, 'coke_brick.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('weed_brick', '大麻ブリック', '大口取引用の1kg大麻ブリック。所持は違法。', NULL, 1000, 'weed_brick.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('coke_small_brick', 'コカインパッケージ', '取引や運搬に使われる小型のコカインパッケージ。所持は違法。', NULL, 350, 'coke_small_brick.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('oxy', '処方オキシ', '医療用の鎮痛剤。乱用は違法。', NULL, 0, 'oxy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 30, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('meth', 'メス', '摂取すると一時的に多幸感を得られる違法薬物。', NULL, 100, 'meth_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -60}'),
('rolling_paper', '巻紙', 'タバコや大麻を巻くための専用ペーパー。', NULL, 0, 'rolling_paper.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('weed_whitewidow', 'ホワイトウィドウ2g', '2g入りのホワイトウィドウ大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('weed_skunk', 'スカンク2g', '2g入りのスカンク大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('weed_purplehaze', 'パープルヘイズ2g', '2g入りのパープルヘイズ大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('weed_ogkush', 'OGクッシュ2g', '2g入りのOGクッシュ大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('weed_amnesia', 'アムネシア2g', '2g入りのアムネシア大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 0, "armor": 0, "hunger": 0, "thirst": 0, "stress": -70}'),
('weed_ak47', 'AK47 2g', '2g入りのAK47大麻。所持は違法。', NULL, 200, 'weed_baggy.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_whitewidow_seed', 'ホワイトウィドウの種', 'ホワイトウィドウ大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_skunk_seed', 'スカンクの種', 'スカンク大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_purplehaze_seed', 'パープルヘイズの種', 'パープルヘイズ大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_ogkush_seed', 'OGクッシュの種', 'OGクッシュ大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_amnesia_seed', 'アムネシアの種', 'アムネシア大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_ak47_seed', 'AK47の種', 'AK47大麻の種子。栽培は違法。', NULL, 0, 'weed_seed.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('empty_weed_bag', '空の大麻袋', '小さな空の袋。大麻の保管や運搬に使用される。', NULL, 0, 'weed_baggy_empty.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('weed_nutrition', '植物用肥料', '大麻などの植物栽培に使う肥料。', NULL, 2000, 'weed_nutrition.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('plastic', 'プラスチック', 'リサイクル可能な素材。クラフト材料として利用できる。', NULL, 100, 'plastic.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('metalscrap', '金属スクラップ', 'クラフトや修理に使える金属の破片。', NULL, 100, 'metalscrap.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('copper', '銅', 'クラフトや修理に使える銅素材。', NULL, 100, 'copper.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('aluminum', 'アルミニウム', 'クラフトや修理に使えるアルミ素材。', NULL, 100, 'aluminum.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('aluminumoxide', 'アルミニウム粉末', '混合やクラフトに使うアルミニウムの粉末。', NULL, 100, 'aluminumoxide.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('iron', '鉄', 'クラフトや修理に使える鉄素材。', NULL, 100, 'iron.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('ironoxide', '鉄粉', '混合やクラフトに使う鉄の粉末。', NULL, 100, 'ironoxide.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('steel', '鋼鉄', 'クラフトや修理に使える鋼鉄素材。', NULL, 100, 'steel.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('rubber', 'ゴム', 'クラフトや修理に使えるゴム素材。', NULL, 100, 'rubber.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('glass', 'ガラス', '壊れやすい素材。クラフト材料として利用できる。', NULL, 100, 'glass.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('lockpick', 'ピッキングツール', '鍵の解錠や侵入に使える道具。', NULL, 300, 'lockpick.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('advancedlockpick', '高性能ピッキングツール', 'より複雑な鍵の解錠や侵入に使える高性能な道具。', NULL, 500, 'advancedlockpick.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('electronickit', '電子キット', '電子工作やクラフトに使える部品セット。', NULL, 100, 'electronickit.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('gatecrack', 'ゲートクラック', '電子ゲートやセキュリティの突破に使うソフトウェア。', NULL, 0, 'usb_device.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('thermite', 'サーミット', '高温で物体を焼き切ることができる化学物質。', NULL, 1000, 'thermite.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('trojan_usb', 'トロイのUSB', 'システムのシャットダウンやハッキングに使うUSBデバイス。', NULL, 0, 'usb_device.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('screwdriverset', 'ツールキット', 'ネジ回しや修理に使える工具セット。', NULL, 1000, 'screwdriverset.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('drill', 'ドリル', '穴あけや破壊作業に使う電動工具。', NULL, 20000, 'drill.png', 5, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('nitrous', 'ニトロ', '車両の加速性能を一時的に大幅アップさせる装置。', NULL, 1000, 'nitrous.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('repairkit', '修理キット', '車両の修理に使えるツールボックス。', NULL, 2500, 'repairkit.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('advancedrepairkit', '高性能修理キット', 'より高度な車両修理が可能なツールボックス。', NULL, 4000, 'advancedkit.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('cleaningkit', 'クリーニングキット', '車両の洗浄やメンテナンスに使える清掃用具。', NULL, 250, 'cleaningkit.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('tunerlaptop', 'チューナーチップ', '車両の性能を調整・強化できる電子チップ。', NULL, 2000, 'tunerchip.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('harness', 'レーシングハーネス', '車両乗車時の安全性を高めるレーシング用ハーネス。', NULL, 1000, 'harness.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('jerry_can', 'ジェリカン20L', '20リットルの燃料が入った携行缶。', NULL, 20000, 'jerry_can.png', 5, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('tirerepairkit', 'タイヤ修理キット', 'タイヤのパンク修理に使えるキット。', NULL, 1000, 'tirerepairkit.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_toolbox', '車両用ツールボックス', '車両の状態確認や簡易修理に使える工具箱。', NULL, 1000, 'veh_toolbox.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_armor', '車両用アーマー', '車両の防御力を強化するアーマー。', NULL, 1000, 'veh_armor.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_brakes', '車両用ブレーキ', '車両のブレーキ性能を強化するアップグレードパーツ。', NULL, 1000, 'veh_brakes.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_engine', '車両用エンジン', '車両のエンジン性能を強化するアップグレードパーツ。', NULL, 1000, 'veh_engine.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_suspension', '車両用サスペンション', '車両のサスペンション性能を強化するアップグレードパーツ。', NULL, 1000, 'veh_suspension.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_transmission', '車両用トランスミッション', '車両のトランスミッション性能を強化するアップグレードパーツ。', NULL, 1000, 'veh_transmission.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_turbo', '車両用ターボ', '車両にターボチャージャーを搭載し、加速性能を向上させる。', NULL, 1000, 'veh_turbo.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_interior', '車両用内装', '車両の内装をカスタマイズするアップグレードパーツ。', NULL, 1000, 'veh_interior.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_exterior', '車両用外装', '車両の外装をカスタマイズするアップグレードパーツ。', NULL, 1000, 'veh_exterior.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_wheels', '車両用ホイール', '車両のホイールをカスタマイズするアップグレードパーツ。', NULL, 1000, 'veh_wheels.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_neons', '車両用ネオン', '車両にネオンライトを装着し、外観をドレスアップする。', NULL, 1000, 'veh_neons.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_xenons', '車両用キセノンライト', '車両のヘッドライトをキセノンライトにアップグレードし、視認性を向上させる。', NULL, 1000, 'veh_xenons.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_tint', '車両用ウィンドウティント', '車両の窓にスモークを貼り付け、外観とプライバシーを向上させる。', NULL, 1000, 'veh_tint.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('veh_plates', '車両用ナンバープレート', '車両のナンバープレートをカスタマイズするアップグレードパーツ。', NULL, 1000, 'veh_plates.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('firstaid', '応急処置キット', '負傷した人を治療し、体力を回復させる医療キット。', NULL, 2500, 'firstaid.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('bandage', '包帯', '負傷箇所の止血や治療に使う医療用品。', NULL, 0, 'bandage.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 30, "armor": 0, "hunger": 0, "thirst": 0, "stress": 0}'),
('ifaks', '個人用救急キット', '負傷箇所の治療やストレス軽減に役立つ個人用救急キット。', NULL, 200, 'ifaks.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 80, "armor": 0, "hunger": 0, "thirst": 0, "stress": 0}'),
('painkillers', '鎮痛剤', '痛みを和らげ、一時的に気分を向上させる薬。', NULL, 0, 'painkillers.png', 50, 'recovery', FALSE, TRUE, 100, FALSE, FALSE, '{"hp": 50, "armor": 0, "hunger": 0, "thirst": 0, "stress": 0}'),
('walkstick', '杖', '歩行補助や近接戦闘に使える杖。', NULL, 1000, 'walkstick.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('phone', '携帯電話', '連絡や情報収集に使える一般的な携帯電話。', NULL, 700, 'phone.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('radio', 'ラジオ', '無線通信や特定の周波数帯の受信に使える機器。', NULL, 2000, 'radio.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('iphone', 'iPhone', '高価なスマートフォン。連絡や様々なアプリ利用に使える。', NULL, 1000, 'iphone.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('samsungphone', 'Samsung S10', '高価なスマートフォン。連絡や様々なアプリ利用に使える。', NULL, 1000, 'samsungphone.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('laptop', 'ノートパソコン', '高価なポータブルコンピュータ。様々な作業や情報収集に使える。', NULL, 4000, 'laptop.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('tablet', 'タブレット', '高価な携帯端末。情報収集やエンターテイメントに使える。', NULL, 2000, 'tablet.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('fitbit', 'フィットビット', '健康管理や運動記録に役立つウェアラブルデバイス。', NULL, 500, 'fitbit.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('radioscanner', '無線スキャナー', '警察無線などの特定の無線通信を傍受できる機器。', NULL, 1000, 'radioscanner.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('pinger', 'ピンガー', '携帯電話と併用して自分の位置情報を送信できる装置。', NULL, 1000, 'pinger.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('cryptostick', 'クリプトスティック', '仮想通貨を保管するUSBデバイス。高額な価値がある場合がある。', NULL, 200, 'cryptostick.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('rolex', 'ゴールデンウォッチ', '高価な金の腕時計。', NULL, 1500, 'rolex.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('diamond_ring', 'ダイヤモンドリング', '高価なダイヤモンドの指輪。', NULL, 1500, 'diamond_ring.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('diamond', 'ダイヤモンド', '高価な宝石。', NULL, 1000, 'diamond.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('goldchain', 'ゴールドチェーン', '高価な金のチェーン。', NULL, 1500, 'goldchain.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('tenkgoldchain', '10kゴールドチェーン', '10カラットの金のチェーン。', NULL, 2000, '10kgoldchain.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('goldbar', 'ゴールドバー', '高価な金のバー。', NULL, 7000, 'goldbar.png', 5, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('armor', 'アーマー', '一定の防御力を提供する装備。', NULL, 5000, 'armor.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('heavyarmor', 'ヘビーアーマー', '一定の防御力を提供する装備。', NULL, 5000, 'armor.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('handcuffs', '手錠', '人を拘束するための道具。', NULL, 100, 'handcuffs.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('police_stormram', 'ストームラム', 'ドアを破壊するためのツール。', NULL, 18000, 'police_stormram.png', 5, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('empty_evidence_bag', '空の証拠袋', 'DNAサンプルや弾丸の殻などの証拠を保管するために使用される。', NULL, 0, 'evidence.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('filled_evidence_bag', '証拠袋', '犯罪の犯人を特定するために使用される証拠が入った袋。', NULL, 200, 'evidence.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('firework1', '2Brothers', '花火。', NULL, 1000, 'firework1.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('firework2', 'Poppelers', '花火。', NULL, 1000, 'firework2.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('firework3', 'WipeOut', '花火。', NULL, 1000, 'firework3.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('firework4', 'Weeping Willow', '花火。', NULL, 1000, 'firework4.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('dendrogyra_coral', 'Dendrogyra', '柱状のサンゴとも呼ばれる。', NULL, 1000, 'dendrogyra_coral.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('antipatharia_coral', 'Antipatharia', '黒いサンゴやとげサンゴとも呼ばれる。', NULL, 1000, 'antipatharia_coral.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('diving_gear', 'ダイビングギア', '酸素タンクとリブレスなどのダイビング用機器。', NULL, 30000, 'diving_gear.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('diving_fill', 'ダイビングチューブ', '酸素タンクとリブレスなどのダイビング用機器。', NULL, 3000, 'diving_tube.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('casinochips', 'カジノチップ', 'カジノでの賭けに使用されるチップ。', NULL, 0, 'casinochips.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('stickynote', 'ステッキーノート', '何かを思い出すのに便利なステッキーノート。', NULL, 0, 'stickynote.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('moneybag', 'お金袋', '現金が入った袋。', NULL, 0, 'moneybag.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('parachute', 'パラシュート', '空中で安全に降下するためのパラシュート。', NULL, 30000, 'parachute.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('binoculars', '望遠鏡', '遠くの物を観察するための望遠鏡。', NULL, 600, 'binoculars.png', 50, 'item', FALSE, TRUE, 100, FALSE, FALSE, '{}'),
('lighter', 'ライター', '年末に火を見るのに便利なライター。', NULL, 0, 'lighter.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('certificate', '証明書', 'ある物品を所有していることを証明する証明書。', NULL, 0, 'certificate.png', 50, 'item', FALSE, FALSE, 100, FALSE, FALSE, '{}'),
('markedbills', 'マークされたお金', '犯罪の証拠としてマークされたお金。', NULL, 1000, 'markedbills.png', 1, 'item', TRUE, FALSE, 100, FALSE, FALSE, '{}'),
('labkey', '鍵', '鍵。', NULL, 500, 'labkey.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('printerdocument', '文書', '重要な文書。', NULL, 500, 'printerdocument.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('newscam', 'ニュースカメラ', 'ニュースで使用されるカメラ。', NULL, 100, 'newscam.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('newsmic', 'ニュースマイク', 'ニュースで使用されるマイク。', NULL, 100, 'newsmic.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('newsbmic', 'ブームマイク', '使用可能なブームマイク。', NULL, 100, 'newsbmic.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('item_bench', '作業台', 'アイテムをクラフトするための作業台。', NULL, 15000, 'workbench.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}'),
('attachment_bench', 'アタッチメント作業台', '武器アタッチメントをクラフトできる専用作業台。カスタマイズの幅が広がる。', NULL, 15000, 'attworkbench.png', 1, 'item', TRUE, TRUE, 100, FALSE, FALSE, '{}');