DGCore = DGCore or {}
DGCore.Constant = DGCore.Constant or {}

DGCore.Constant.Tables = {
    User = 'user',
    Player = 'player',
    Job = 'job',
    JobGrade = 'job_grade',
    Gang = 'gang',
    GangGrade = 'gang_grade',
    Item = 'item',
    Weapon = 'weapon',
    PlayerStatus = 'player_status',
    PlayerItem = 'player_item',
    PlayerItemStatus = 'player_item_status',
    PlayerWallet = 'player_wallet',
    PlayerBank = 'player_bank',
    PlayerPhone = 'player_phone',
    PlayerJob = 'player_job',
    PlayerGang = 'player_gang',
    Bans = 'bans',
}

DGCore.Constant.Queries = {
    User = {
        SelectById = string.format("SELECT * FROM %s WHERE id = ?", DGCore.Constant.Tables.User),
        SelectByRockStartId = string.format("SELECT * FROM %s WHERE rockstart_id = ?", DGCore.Constant.Tables.User),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.User),
        ExistsRockStartId = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE rockstart_id = ?) AS uniqueCheck", DGCore.Constant.Tables.User),
        Insert = string.format("INSERT INTO %s (id, rockstart_id, is_admin, is_ban, ban_reason, is_whitelist) VALUES (?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.User),
        Update = string.format("UPDATE %s SET is_admin = ?, is_ban = ?, ban_reason = ?, is_whitelist = ? WHERE id = ?", DGCore.Constant.Tables.User),
    },
    Player = {
        SelectById = string.format("SELECT * FROM %s WHERE id = ?", DGCore.Constant.Tables.Player),
        SelectByUserId = string.format("SELECT * FROM %s WHERE user_id = ?", DGCore.Constant.Tables.Player),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.Player),
        Insert = string.format("INSERT INTO %s (id, firstname, lastname, birthday, gender, nationality, slot, is_deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.Player),
        Update = string.format("UPDATE %s SET firstname = ?, lastname = ?, birthday = ?, gender = ?, nationality = ?, slot = ?, is_deleted = ? WHERE id = ?", DGCore.Constant.Tables.Player),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.Player),
    },
    Job = {
        SelectAll = string.format("SELECT * FROM %s", DGCore.Constant.Tables.Job),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.Job),
        Insert = string.format("INSERT INTO %s (id, event, label, defaultDuty, offDuty) VALUES (?, ?, ?, ?, ?)", DGCore.Constant.Tables.Job),
        Update = string.format("UPDATE %s SET event = ?, label = ?, defaultDuty = ?, offDuty = ? WHERE id = ?", DGCore.Constant.Tables.Job),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.Job),
    },
    JobGrade = {
        SelectByJobId = string.format("SELECT * FROM %s WHERE job_id = ?", DGCore.Constant.Tables.JobGrade),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.JobGrade),
        Insert = string.format("INSERT INTO %s (id, job_id, level, label, payment, isboss) VALUES (?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.JobGrade),
        Update = string.format("UPDATE %s SET job_id = ?, level = ?, label = ?, payment = ?, isboss = ? WHERE id = ?", DGCore.Constant.Tables.JobGrade),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.JobGrade),
    },
    Gang = {
        SelectAll = string.format("SELECT * FROM %s", DGCore.Constant.Tables.Gang),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.Gang),
        Insert = string.format("INSERT INTO %s (id, label) VALUES (?, ?)", DGCore.Constant.Tables.Gang),
        Update = string.format("UPDATE %s SET label = ? WHERE id = ?", DGCore.Constant.Tables.Gang),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.Gang),
    },
    GangGrade = {
        SelectByGangId = string.format("SELECT * FROM %s WHERE gang_id = ?", DGCore.Constant.Tables.GangGrade),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.GangGrade),
        Insert = string.format("INSERT INTO %s (id, gang_id, level, label) VALUES (?, ?, ?, ?)", DGCore.Constant.Tables.GangGrade),
        Update = string.format("UPDATE %s SET gang_id = ?, level = ?, label = ? WHERE id = ?", DGCore.Constant.Tables.GangGrade),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.GangGrade),
    },
    Item = {
        SelectAll = string.format("SELECT * FROM %s", DGCore.Constant.Tables.Item),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.Item),
        Insert = string.format("INSERT INTO %s (id, name, label, weight, category, ammotype, image, isstack, stacksize, isrightclick, isshouldclose, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.Item),
        Update = string.format("UPDATE %s SET name = ?, label = ?, weight = ?, category = ?, ammotype = ?, image = ?, isstack = ?, stacksize = ?, isrightclick = ?, isshouldclose = ?, description = ? WHERE id = ?", DGCore.Constant.Tables.Item),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.Item),
    },
    Weapon = {
        SelectAll = string.format("SELECT * FROM %s", DGCore.Constant.Tables.Weapon),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.Weapon),
        ExistsName = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE name = ?)", DGCore.Constant.Tables.Weapon),
        Insert = string.format("INSERT INTO %s (id, item_id, damage, recoil, firerate, magazine_size, weapon_category) VALUES (?, ?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.Weapon),
        Update = string.format("UPDATE %s SET item_id = ?, damage = ?, recoil = ?, firerate = ?, magazine_size = ?, weapon_category = ? WHERE id = ?", DGCore.Constant.Tables.Weapon),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.Weapon),
    },
    PlayerStatus = {
        SelectById = string.format("SELECT * FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerStatus),
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerStatus),
        SelectJoinStatusByPlayerId = string.format("SELECT ps.* FROM %s p LEFT JOIN %s ps ON p.id = ps.player_id WHERE p.id = ?", DGCore.Constant.Tables.Player, DGCore.Constant.Tables.PlayerStatus),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerStatus),
        Insert = string.format("INSERT INTO %s (id, player_id, hunger, thirst, stress, isdead, iscrippling, armor, ishandcuff, istracker, isinjail) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.PlayerStatus),
        Update = string.format("UPDATE %s SET hunger = ?, thirst = ?, stress = ?, isdead = ?, iscrippling = ?, armor = ?, ishandcuff = ?, istracker = ?, injail = ? WHERE id = ?", DGCore.Constant.Tables.PlayerStatus),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerStatus),
    },
    PlayerItem = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerItem),
        SelectJoinItemByPlayerId = string.format("SELECT pi.*, i.*, pis.id AS pis_id, pis.durability AS pis_durability, pis.is_equipped AS pis_is_equipped, pis.use_count AS pis_use_count FROM %s pi JOIN %s i ON pi.item_id = i.id LEFT JOIN %s pis ON pi.id = pis.player_item_id WHERE pi.player_id = ?", DGCore.Constant.Tables.PlayerItem, DGCore.Constant.Tables.Item, DGCore.Constant.Tables.PlayerItemStatus),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerItem),
        Insert = string.format("INSERT INTO %s (id, player_id, item_id, slot, quantity, isjail) VALUES (?, ?, ?, ?, ?, ?)", DGCore.Constant.Tables.PlayerItem),
        Update = string.format("UPDATE %s SET slot = ?, quantity = ?, isjail = ? WHERE id = ?", DGCore.Constant.Tables.PlayerItem),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerItem),
    },
    PlayerItemStatus = {
        SelectByPlayerItemId = string.format("SELECT * FROM %s WHERE player_item_id = ?", DGCore.Constant.Tables.PlayerItemStatus),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerItemStatus),
        Insert = string.format("INSERT INTO %s (id, player_item_id, durability, is_equipped, use_count) VALUES (?, ?, ?, ?, ?)", DGCore.Constant.Tables.PlayerItemStatus),
        Update = string.format("UPDATE %s SET durability = ?, is_equipped = ?, use_count = ? WHERE id = ?", DGCore.Constant.Tables.PlayerItemStatus),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerItemStatus),
    },
    PlayerWallet = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerWallet),
        SelectJoinWalletByPlayerId = string.format("SELECT pw.* FROM %s p LEFT JOIN %s pw ON p.id = pw.player_id WHERE p.id = ?", DGCore.Constant.Tables.Player, DGCore.Constant.Tables.PlayerWallet),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?)", DGCore.Constant.Tables.PlayerWallet),
        Insert = string.format("INSERT INTO %s (id, player_id, cash, crypto) VALUES (?, ?, ?, ?)", DGCore.Constant.Tables.PlayerWallet),
        Update = string.format("UPDATE %s SET cash = ?, crypto = ? WHERE id = ?", DGCore.Constant.Tables.PlayerWallet),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerWallet),
    },
    PlayerBank = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerBank),
        SelectJoinBankByPlayerId = string.format("SELECT pb.* FROM %s p LEFT JOIN %s pb ON p.id = pb.player_id WHERE p.id = ?", DGCore.Constant.Tables.Player, DGCore.Constant.Tables.PlayerBank),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerBank),
        ExistsByAccountNumber = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE account_number = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerBank),
        Insert = string.format("INSERT INTO %s (id, player_id, name, account_number, balance) VALUES (?, ?, ?, ?, ?)", DGCore.Constant.Tables.PlayerBank),
        Update = string.format("UPDATE %s SET name = ?, account_number = ?, balance = ? WHERE id = ?", DGCore.Constant.Tables.PlayerBank),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerBank),
    },
    PlayerPhone = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerPhone),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE ID = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerPhone),
        Insert = string.format("INSERT INTO %s (id, player_id, number) VALUES (?, ?, ?)", DGCore.Constant.Tables.PlayerPhone),
        Update = string.format("UPDATE %s SET player_id = ?, number = ? WHERE id = ?", DGCore.Constant.Tables.PlayerPhone),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerPhone),
    },
    PlayerJob = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerJob),
        SelectJoinJobByPlayerId = string.format("SELECT pj.*, j.*, jg.id AS jg_id, jg.level AS jg_level, jg.label AS jg_label, jg.payment AS jg_payment, jg.isboss AS jg_isboss FROM %s pj JOIN %s j ON pj.job_id = j.id JOIN %s jg ON pj.job_grade_id = jg.id WHERE pj.player_id = ?", DGCore.Constant.Tables.PlayerJob, DGCore.Constant.Tables.Job, DGCore.Constant.Tables.JobGrade),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerJob),
        Insert = string.format("INSERT INTO %s (id, player_id, job_id, job_grade_id) VALUES (?, ?, ?, ?)", DGCore.Constant.Tables.PlayerJob),
        Update = string.format("UPDATE %s SET job_id = ?, job_grade_id = ? WHERE id = ?", DGCore.Constant.Tables.PlayerJob),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerJob),
    },
    PlayerGang = {
        SelectByPlayerId = string.format("SELECT * FROM %s WHERE player_id = ?", DGCore.Constant.Tables.PlayerGang),
        SelectJoinGangByPlayerId = string.format("SELECT pg.*, g.*, gg.level AS gg_level, gg.label AS gg_label FROM %s pg JOIN %s g ON pg.gang_id = g.id JOIN %s gg ON pg.gang_grade_id = gg.id WHERE pg.player_id = ?", DGCore.Constant.Tables.PlayerGang, DGCore.Constant.Tables.Gang, DGCore.Constant.Tables.GangGrade),
        Exists = string.format("SELECT EXISTS(SELECT 1 FROM %s WHERE id = ?) AS uniqueCheck", DGCore.Constant.Tables.PlayerGang),
        Insert = string.format("INSERT INTO %s (id, player_id, gang_id, gang_grade_id) VALUES (?, ?, ?, ?)", DGCore.Constant.Tables.PlayerGang),
        Update = string.format("UPDATE %s SET gang_id = ?, gang_grade_id = ? WHERE id = ?", DGCore.Constant.Tables.PlayerGang),
        Delete = string.format("DELETE FROM %s WHERE id = ?", DGCore.Constant.Tables.PlayerGang),
    },
}
